name: Rust Project Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache APT packages and lists
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Rust toolchain
        uses: actions/cache@v3
        with:
          path: ~/.rustup/toolchains
          key: ${{ runner.os }}-rust-toolchain-${{ hashFiles('rust-toolchain') }}
          restore-keys: |
            ${{ runner.os }}-rust-toolchain-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # sudo apt install build-essential
          # sudo apt install pkg-config libssl-dev
          # sudo apt install liblapack-dev libblas-dev libopenblas-dev
          sudo apt-get install -y graphviz

      - name: Cache ONNX Runtime binaries
        uses: actions/cache@v3
        with:
          path: ./onnxruntime-linux-x64
          key: onnxruntime-${{ runner.os }}-1.20.1

      - name: Download and extract ONNX Runtime binaries if not cached
        # if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sL https://github.com/microsoft/onnxruntime/releases/download/v1.20.1/onnxruntime-linux-x64-1.20.1.tgz -o onnxruntime.tgz
          mkdir -p onnxruntime-linux-x64
          tar -xzf onnxruntime.tgz -C onnxruntime-linux-x64 --strip-components=1
  
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cargo installs
        run: cargo install cargo-depgraph cargo-machete

      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Format the code
        env:
          ORT_DYLIB_PATH: ./onnxruntime-linux-x64/lib/libonnxruntime.so
        run: make prep

      - name: Run tests
        env:
          ORT_DYLIB_PATH: ./onnxruntime-linux-x64/lib/libonnxruntime.so
        run: make test
